export let GET_RECIPES_PENDING = "GET_RECIPES_PENDING"
export let GET_RECIPES_SUCCESS = "GET_RECIPES_SUCCESS"
export let GET_RECIPES_ERROR = "GET_RECIPES_ERROR"

export let POST_RECIPES_PENDING = "POST_RECIPES_PENDING"
export let POST_RECIPES_SUCCESS = "POST_RECIPES_SUCCESS"
export let POST_RECIPES_ERROR = "POST_RECIPES_ERROR"

export let DELETE_RECIPES_PENDING = "DELETE_RECIPES_PENDING"
export let DELETE_RECIPES_SUCCESS = "DELETE_RECIPES_SUCCESS"
export let DELETE_RECIPES_ERROR = "DELETE_RECIPES_ERROR"

export let UPDATE_RECIPES_PENDING = "UPDATE_RECIPES_PENDING"
export let UPDATE_RECIPES_SUCCESS = "UPDATE_RECIPES_SUCCESS"
export let UPDATE_RECIPES_ERROR = "UPDATE_RECIPES_ERROR"


